namespace Empire
{
    public class NPC1:BlackmarketBuyer{}
    public class NPC2:BlackmarketBuyer{}
    public class NPC3:BlackmarketBuyer{}
    public class NPC4:BlackmarketBuyer{}
    public class NPC5:BlackmarketBuyer{}
    public class NPC6:BlackmarketBuyer{}
    public class NPC7:BlackmarketBuyer{}
    public class NPC8:BlackmarketBuyer{}
    public class NPC9:BlackmarketBuyer{}
    public class NPC10:BlackmarketBuyer{}
    public class NPC11:BlackmarketBuyer{}
    public class NPC12:BlackmarketBuyer{}
    public class NPC13:BlackmarketBuyer{}
    public class NPC14:BlackmarketBuyer{}
    public class NPC15:BlackmarketBuyer{}
    public class NPC16:BlackmarketBuyer{}
    public class NPC17:BlackmarketBuyer{}
    public class NPC18:BlackmarketBuyer{}
    public class NPC19:BlackmarketBuyer{}
    public class NPC20:BlackmarketBuyer{}
    public class NPC21:BlackmarketBuyer{}
    public class NPC22:BlackmarketBuyer{}
    public class NPC23:BlackmarketBuyer{}
    public class NPC24:BlackmarketBuyer{}
    public class NPC25:BlackmarketBuyer{}
    public class NPC26:BlackmarketBuyer{}
    public class NPC27:BlackmarketBuyer{}
    public class NPC28:BlackmarketBuyer{}
    public class NPC29:BlackmarketBuyer{}
    public class NPC30:BlackmarketBuyer{}
    /*public class NPC31:BlackmarketBuyer{}
    public class NPC32:BlackmarketBuyer{}
    public class NPC33:BlackmarketBuyer{}
    public class NPC34:BlackmarketBuyer{}
    public class NPC35:BlackmarketBuyer{}
    public class NPC36:BlackmarketBuyer{}
    public class NPC37:BlackmarketBuyer{}
    public class NPC38:BlackmarketBuyer{}
    public class NPC39:BlackmarketBuyer{}
    public class NPC40:BlackmarketBuyer{}
    public class NPC41:BlackmarketBuyer{}
    public class NPC42:BlackmarketBuyer{}
    public class NPC43:BlackmarketBuyer{}
    public class NPC44:BlackmarketBuyer{}
    public class NPC45:BlackmarketBuyer{}
    public class NPC46:BlackmarketBuyer{}
    public class NPC47:BlackmarketBuyer{}
    public class NPC48:BlackmarketBuyer{}
    public class NPC49:BlackmarketBuyer{}
    public class NPC50:BlackmarketBuyer{}*/

}